export const harga = [
  {
    komoditas: "BERAS",
    bulan: 10,
    satuan: "KG",
    harga: 10699,
  },
  {
    komoditas: "GULA",
    bulan: 10,
    satuan: "KG",
    harga: 13260,
  },
  {
    komoditas: "Minyak Goreng",
    bulan: 10,
    satuan: "LT",
    harga: 9785,
  },
  {
    komoditas: "Tepung Terigu",
    bulan: 10,
    satuan: "KG",
    harga: 13260,
  },
  {
    komoditas: "Kedelai",
    bulan: 10,
    satuan: "KG",
    harga: 10606,
  },
  {
    komoditas: "Daging Sapi",
    bulan: 10,
    satuan: "KG",
    harga: 120357,
  },
  {
    komoditas: "Daging Ayam",
    bulan: 10,
    satuan: "KG",
    harga: 33751,
  },
  {
    komoditas: "Telur Ayam",
    bulan: 10,
    satuan: "KG",
    harga: 27139,
  },
  {
    komoditas: "Cabe",
    bulan: 10,
    satuan: "KG",
    harga: 48376,
  },
  {
    komoditas: "Bawang",
    bulan: 10,
    satuan: "KG",
    harga: 36239,
  },
  {
    komoditas: "Susu",
    bulan: 10,
    satuan: "GR",
    harga: 10914,
  },
  {
    komoditas: "Jagung",
    bulan: 10,
    satuan: "KG",
    harga: 7852,
  },
  {
    komoditas: "Ikan",
    bulan: 10,
    satuan: "KG",
    harga: 61490,
  },
  {
    komoditas: "Garam",
    bulan: 10,
    satuan: "KG",
    harga: 9760,
  },
  {
    komoditas: "Mie Instan",
    bulan: 10,
    satuan: "BKS",
    harga: 2615,
  },
  {
    komoditas: "Kacang",
    bulan: 10,
    satuan: "KG",
    harga: 26812,
  },
  {
    komoditas: "Ketela Pohon",
    bulan: 10,
    satuan: "KG",
    harga: 5989,
  },

  {
    komoditas: "BERAS",
    bulan: 11,
    satuan: "KG",
    harga: 10693,
  },
  {
    komoditas: "GULA",
    bulan: 11,
    satuan: "KG",
    harga: 13264,
  },
  {
    komoditas: "Minyak Goreng",
    bulan: 11,
    satuan: "LT",
    harga: 12223,
  },
  {
    komoditas: "Tepung Terigu",
    bulan: 11,
    satuan: "KG",
    harga: 9785,
  },
  {
    komoditas: "Kedelai",
    bulan: 11,
    satuan: "KG",
    harga: 10599,
  },
  {
    komoditas: "Daging Sapi",
    bulan: 11,
    satuan: "KG",
    harga: 120357,
  },
  {
    komoditas: "Daging Ayam",
    bulan: 11,
    satuan: "KG",
    harga: 33831,
  },
  {
    komoditas: "Telur Ayam",
    bulan: 11,
    satuan: "KG",
    harga: 27165,
  },
  {
    komoditas: "Cabe",
    bulan: 11,
    satuan: "KG",
    harga: 49207,
  },
  {
    komoditas: "Bawang",
    bulan: 11,
    satuan: "KG",
    harga: 36071,
  },
  {
    komoditas: "Susu",
    bulan: 11,
    satuan: "GR",
    harga: 10899,
  },
  {
    komoditas: "Jagung",
    bulan: 11,
    satuan: "KG",
    harga: 7843,
  },
  {
    komoditas: "Ikan",
    bulan: 11,
    satuan: "KG",
    harga: 62730,
  },
  {
    komoditas: "Garam",
    bulan: 11,
    satuan: "KG",
    harga: 9782,
  },
  {
    komoditas: "Mie Instan",
    bulan: 11,
    satuan: "BKS",
    harga: 2616,
  },
  {
    komoditas: "Kacang",
    bulan: 11,
    satuan: "KG",
    harga: 26736,
  },
  {
    komoditas: "Ketela Pohon",
    bulan: 11,
    satuan: "KG",
    harga: 6009,
  },
];
